config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'diaries#index'
  resources :diaries do
    resources :comments, only: :create
    collection do
      get 'search'
      get 'kyokumenzu'
    end
  end
  resources :users, only: [:show, :edit, :update]
  resources :tags, only: [:create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :diary, dependent: :destroy
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments
  has_many :diary_tag_relations, dependent: :destroy
  has_many :tags, through: :diary_tag_relations

  validates :title, presence: true

  def self.search(search)
    if search != ""
      Diary.where(['title LIKE(?) OR content LIKE(?)', "%#{search}%", "%#{search}%"])
    else
      Diary.all
    end
  end
end

app/models/diary_tag.rb
class DiaryTag

  include ActiveModel::Model
  attr_accessor :title, :content, :image, :tag_name, :user_id, :diary_id

  def save
    diary = Diary.create(title: title, content: content, image: image, user_id: user_id)
    tag = Tag.where(tag_name: tag_name).first_or_initialize
    tag.save

    DiaryTagRelation.create(diary_id: diary.id, tag_id: tag.id)
  end

  def create
    tag = Tag.where(tag_name: tag_name).first_or_initialize
    tag.save

    DiaryTagRelation.create(diary_id: diary_id, tag_id: tag.id)
  end
end

app/models/diary_tag_relation.rb
class DiaryTagRelation < ApplicationRecord
  belongs_to :diary
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :diary_tag_relations, dependent: :destroy
  has_many :diaries, through: :diary_tag_relations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :diaries
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :introduction])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    # binding.pry
    comment = Comment.create(comment_params)
    redirect_to "/diaries/#{comment.diary.id}"
  end

  private

  def comment_params
    params.require(:comment).permit(:comment).merge(diary_id: params[:diary_id], user_id: current_user.id)
  end

end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController

  def index
    @diaries = Diary.all.includes(:user).order("created_at DESC")
    @users = User.all
    @tags = Tag.all
  end

  def new
    @diary = DiaryTag.new
  end

  def create
    @diary = DiaryTag.new(diary_tag_params)
    if @diary.valid?
      @diary.save
      return redirect_to root_path
    else
      render "new"
    end
  end

  def show
    @diary = Diary.find(params[:id])
    @comment = Comment.new
    @comments = @diary.comments.includes(:user)
    @tag = Tag.new
  end

  def edit
    @diary = Diary.find(params[:id])
  end

  def update
    diary = Diary.find(params[:id])
    diary.update(diary_params)
    redirect_to diary_path
  end

  def search
    @diaries = Diary.search(params[:keyword])
    @users = User.all
    @tags = Tag.all
    render action: "index"
  end

  def destroy
    @diary = Diary.find(params[:id])
    if @diary.destroy
      redirect_to user_path(@diary.user.id)
    else
      render diary_path(@diary.id)
    end
  end

  def kyokumenzu
  end

  private

  def diary_tag_params
    params.require(:diary_tag).permit(:title, :content, :image, :tag_name).merge(user_id: current_user.id)
  end

  def diary_params
    params.require(:diary).permit(:title, :content, :image).merge(user_id: current_user.id)
  end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def create
    @tag = DiaryTag.new(tag_params)
    if @tag.valid?
      @tag.create
    end
    redirect_to diary_path(@tag.diary_id)
  end

  def show
    @tag = Tag.find(params[:id])
  end

  private

  def tag_params
    diary_id = params.require(:tag).permit(diary_ids: [])
    params.require(:tag).permit(:tag_name).merge(diary_id: diary_id["diary_ids"][0])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @diaries = @user.diaries
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diaries/_diary-list.html.erb
<div class="diary-item">
  <div class="diary-item-date">
    <%= diary.updated_at %>
  </div>
  <div class="diary-item-title">
    <%= link_to "#{diary.title}", diary_path(diary.id) %>
  </div>
  <div class="diary-item-image">
    <% if diary.image.attached? %>
      <%= image_tag diary.image.variant(resize: '350x350') %>
    <% else %>
      <%= "NO IMAGE" %>
    <% end %>
  </div>
  <div class="diary-item-user-name">
    <%= link_to "by #{diary.user.name}", user_path(diary.user.id) %>
  </div>
</div>

app/views/diaries/edit.html.erb
<div class="diary-content">

  <div class="diary-title">
    記事の更新
  </div>

  <%= form_with model: @diary, local: true do |f| %>
  <div class="diary-form">
    <div class="field">
      <%= f.label "タイトル" %><br/>
      <%= f.text_field :title, class: "text-form" %>
    </div>
    <div class="field">
      <%= f.label "画像" %><br/>
      <%= f.file_field :image %>
    </div>
    <div class="field">
      <%= f.label "内容" %><br/>
      <%= f.text_area :content, class: "text-area" %>
    </div>
    <div class="actions">
      <%= f.submit "更新" %>
    </div>
  </div>
  <% end %>
</div>

app/views/diaries/index.html.erb
<div class="body-container">

  <div class="side-bar">
    <div class="side-bar-container">
      <%= form_with url: search_diaries_path, method: :get, class: "search-form", local: true do |form| %>
        <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
        <%= form.submit "検索", class: "search-btn" %>
      <% end %>

      <div class="user-name-list-title">
        <b><%= "ユーザ一覧" %></b>
      </div>
      <ul class="user-name-list">
        <% @users.each do |user| %>
          <li class="user-name">
            <%= link_to "#{user.name}", user_path(user.id) %>
          </li>
        <% end %>
      </ul>

      <div class="tag-name-list-title">
        <b><%= "タグ一覧" %></b>
      </div>
      <ul class="tag-name-list">
        <% @tags.each do |tag| %>
          <li class="side-bar-tag-name">
            <%= link_to "#{tag.tag_name}", tag_path(tag.id) %><%= "（#{tag.diaries.count}）" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="main-bar">
    <div class="main-bar-title">
      投稿記事一覧
    </div>
    <div class="diary-box">
      <div class="diary-items">
        <%= render partial: 'diary-list', collection: @diaries, as: "diary" %>
      </div>
      <div class="main-bar-button">
      < 前のページ 次のページ>
      </div>
    </div>
  </div>

</div>

app/views/diaries/kyokumenzu.html.erb
<div class="kyokumenzu-container">

<h1 class="kyokumenzu-title">局面図作成ページ</h1>
<div class="my-canvas">
  <canvas id="myCanvas"></canvas>
</div>

<a id="download-link" href="" download="" class="download-link">局面図をダウンロード</a>
<%= link_to "戻る", new_diary_path, class: "download-link" %>
</div>

app/views/diaries/new.html.erb
<div class="diary-content">
  <div class="diary-title">
  新規投稿ページ
  </div>

    <%= form_with model: @diary, url: diaries_path, local: true do |f| %>
    <div class="diary-form">
      <div class="field">
        <%= f.label "タイトル" %><br/>
        <%= f.text_field :title, class: "text-form" %>
      </div>
      <div class="field">
        <%= f.label "画像" %><br/>
        <%= f.file_field :image %>
      </div>
      <div class="field">
        <%= f.label "内容" %><br/>
        <%= f.text_area :content, class: "text-area" %>
      </div>
      <div class="field">
        <%= f.label "タグ" %><br/>
        <%= f.text_field :tag_name, class: "text-form" %><br/>
      </div>
      <div class="actions">
        <%= f.submit "投稿" %>
      </div>
      <div class="actions">
        <%= link_to "局面図作成", kyokumenzu_diaries_path %>
      </div>
    </div>

    <% end %>
</div>

app/views/diaries/show.html.erb
<div class="show-diary-container">

  <div class="show-diary-title"><%= @diary.title %></div>
  <div class="tag-container">
    <% @diary.tags.each do |tag| %>
      <div class="tag-name">
        <%= tag.tag_name %>
      </div>
    <% end %>
    <%= form_with model: @tag, url: tags_path, local: true do |f| %>
    <div class="tag-forms">
        <%= f.text_field :tag_name, class: "tag-form" %>
        <%= f.submit "＋", class: "tag-button" %>
        <%= hidden_field_tag "tag[diary_ids][]", @diary.id %>
        </div>
    <% end %>
  </div>

  <div class="show-diary-content">
    <div class="show-diary-image">
      <%= image_tag @diary.image.variant(resize: '600x600') if @diary.image.attached? %>
    </div>
    <div class="show-diary-detail">
      <% if current_user != nil && @diary.user.id == current_user.id %>
        <span class="show-diary-edit-btns">
          <%= link_to "この記事を編集", edit_diary_path(@diary.id), class: "show-diary-edit-btn" %>
          <%= link_to "削除", diary_path(@diary.id), method: :delete, class: "show-diary-edit-btn" %>
        </span>
      <% else %>
        <div class="show-diary-user">
          <%= link_to "#{@diary.user.name}", user_path(@diary.user.id) %>
        </div>
      <% end%>
      <span class="show-diary-text"><%= @diary.content %></span>
    </div>
  </div>

  <div class="comment-area">
    <h1 class="comment-area-title">★投稿コメント一覧★</h1>
    <% @comments.each do |comment| %>
      <% if @diary.user.id == comment.user.id %>
        <div class="comment-text comment-owner">
          <div><%= comment.comment %></div>
          <div class="comment-user-name"><%= comment.user.name %></div>
        </div>
      <% else %>
        <div class="comment-text comment-other">
          <div><%= comment.comment %></div>
          <div class="comment-user-name"><%= comment.user.name %></div>
        </div>
      <% end %>
    <% end %>
    <% if user_signed_in? %>
      <%= form_with model: @comment, url: diary_comments_path(@diary.id), local: true do |f| %>
        <div class="comment-form">
          <%= f.text_area :comment, class: "comment-text-area" %>
          <%= f.submit "コメントする", class: "comment-submit" %>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShogiDiary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <div class="header-content">
      <b><a href="/" class="header-title">SHOGI DIARY</a></b>
      <div class="header-btns">
        <% if user_signed_in? %>
          <%= link_to "#{current_user.name}", user_path(current_user.id), class: "header-btn" %>
          <%= link_to "新規投稿",  new_diary_path, class: "header-btn" %>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "header-btn" %>
        <% else %>
          <%= link_to '新規登録', new_user_registration_path, class: "header-btn" %>
          <%= link_to 'サインイン', new_user_session_path, class: "header-btn" %>
        <% end %>
      </div>
    </div>
  </header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tags/show.html.erb
<div class="show-user-container">

<span class="show-user-diary-list"><%= "”#{@tag.tag_name}”の投稿記事一覧" %><br/>

  <div class="show-user-diaries">
    <%= render partial: 'diaries/diary-list', collection: @tag.diaries, as: "diary" %>
  </div>

</div>

app/views/users/edit.html.erb
<%= form_with model: current_user, local: true do |f| %>
  <div><%= f.label :name %></div>
  <div><%= f.text_field :name %></div>
  <div><%= f.label :email %></div>
  <div><%= f.email_field :email %></div>
  <div><%= f.label :introduction %></div>
  <div><%= f.text_area :introduction %></div>
  <div><%= f.submit "更新"%></div>
<% end %>

app/views/users/show.html.erb
<div class="show-user-container">

  <div class="show-user-detail">
    <p class="show-user-name"><%= "#{@user.name}さんの日記一覧" %></p>
    <p class="show-user-intro"><%= @user.introduction %></p>
  </div>

  <span class="show-user-diary-list"><%= "投稿記事一覧" %><br/>

  <div class="show-user-diaries">
    <%= render partial: 'diaries/diary-list', collection: @diaries, as: "diary" %>
  </div>

</div>